development:
  adapter: clickhouse
  host: localhost
  port: 8123
  database: adsensie_analytics
  username: adsensie
  password: 
  
test:
  adapter: clickhouse
  host: localhost
  port: 8123
  database: adsensie_analytics_test
  username: default
  password: 
  
production:
  adapter: clickhouse
  host: <%= ENV['CLICKHOUSE_HOST'] || 'localhost' %>
  port: 8123
  database: adsensie_analytics
  username: <%= ENV['CLICKHOUSE_USER'] || 'default' %>
  password: <%= ENV['CLICKHOUSE_PASSWORD'] || '' %>
